[package]
name = "sonos-volume-bridge"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
default-run = "sonos-volume-bridge"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
sonos-volume-bridge-domain = { path = "../crates/domain" }
sonos-volume-bridge-integration = { path = "../crates/integration" }
sonos-volume-bridge-platform-audio = { path = "../crates/platform-audio" }
sonos-volume-bridge-sonos = { path = "../crates/sonos" }
sonos-volume-bridge-synchronization = { path = "../crates/synchronization" }
tauri = { version = "2", features = ["image-png", "tray-icon"] }
tauri-plugin-autostart = "2"
tauri-plugin-single-instance = "2"
thiserror.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
tokio.workspace = true
url.workspace = true

[lints]
workspace = true
