#!/usr/bin/env sh
set -eu

if [ -n "${APPLE_SHARED_CERT_PASSWORD:-}" ]; then
  : "${APPLE_CERTIFICATE_PASSWORD:=$APPLE_SHARED_CERT_PASSWORD}"
  : "${APPLE_APP_STORE_CERTIFICATE_PASSWORD:=$APPLE_SHARED_CERT_PASSWORD}"
  : "${APPLE_MAC_INSTALLER_CERTIFICATE_PASSWORD:=$APPLE_SHARED_CERT_PASSWORD}"
fi

export APPLE_CERTIFICATE_PASSWORD
export APPLE_APP_STORE_CERTIFICATE_PASSWORD
export APPLE_MAC_INSTALLER_CERTIFICATE_PASSWORD
